### ISSUE TITLE
itksnap fails to run after loading the module

### ISSUE THREAD

**Issue by steelec** [gdevenyi/neuralabc_modules#1]
/opt/quarantine/itksnap/3.8.0-beta-20181028/install/lib/snap-3.8.0-beta/ITK-SNAP: /usr/lib/x86_64-linux-gnu/libpng12.so.0: version `PNG12_0' not found (required by /opt/quarantine/itksnap/3.8.0-beta-20181028/install/lib/snap-3.8.0-beta/libQt5Gui.so.5)

**Comment by gdevenyi** [comment]
Fixed.
