### ISSUE TITLE
ANTs - .sh files not on path

### ISSUE THREAD

**Issue by steelec** [gdevenyi/neuralabc_modules#16]
shell scripts are one directory up from the bin, in the root /install directory so currently missed by the .lua

from what I see, ANTs also seems to expect all .sh files to be in the bin directory. When manually adding the /install dir to the path and then running:
antsMultivariateTemplateConstruction2.sh
```
-----------------------------------------------------------------------------
 FILE [...removedbyme...]/install/bin/ANTSpexec.sh DOES NOT EXIST -- OR -- IS NOT EXECUTABLE !!! [...removedbyme...]/install/antsMultivariateTemplateConstruction2.sh will terminate.
-----------------------------------------------------------------------------
 if the file is not executable, please change its permissions.
...
...
...
```

**Comment by gdevenyi** [comment]
Fixed.
