### ISSUE TITLE
ANTs - missing shared libs

### ISSUE THREAD

**Issue by steelec** [gdevenyi/neuralabc_modules#2]
ANTS
ANTS: error while loading shared libraries: libitkhdf5_cpp.so.1: cannot open shared object file: No such file or directory
Atropos
Atropos: error while loading shared libraries: libitkhdf5_cpp.so.1: cannot open shared object file: No such file or directory

**Comment by gdevenyi** [comment]
Fixed.

**Comment by DomenicoMessina** [comment]
I have the same error, just after compiled ANTs. Maybe i wrong to set ccmake? Can someone help me? I'm new to the programming world.

**Comment by gdevenyi** [comment]
Please follow the instructions here and if still have problems ask for support from the ANTs developers.

https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS
