### ISSUE TITLE
AFNI - path incorrect and missing libs

### ISSUE THREAD

**Issue by steelec** [gdevenyi/neuralabc_modules#3]
1) current added path points to .../bin, but binaries are one dir up and there is no /bin dir.
2) missing shared library/ies: /opt/quarantine/afni/20190320/install/linux_ubuntu_16_64/3dSeg
/opt/quarantine/afni/20190320/install/linux_ubuntu_16_64/3dSeg: error while loading shared libraries: libXm.so.4: cannot open shared object file: No such file or directory

**Comment by gdevenyi** [comment]
Fixed.

**Comment by steelec** [comment]
shell scripts are one directory up from the bin, in the root install so currently missed by the .lua

**Comment by steelec** [comment]
from what I see, ANTs also seems to expect all .sh files to be in the bin directory. When manually adding the /install dir to the path and then running 
antsMultivariateTemplateConstruction2.sh

```
-----------------------------------------------------------------------------
 FILE [...removedbyme...]/install/bin/ANTSpexec.sh DOES NOT EXIST -- OR -- IS NOT EXECUTABLE !!! [...removedbyme...]/install/antsMultivariateTemplateConstruction2.sh will terminate.
-----------------------------------------------------------------------------
 if the file is not executable, please change its permissions.
...
...
...
```
