### ISSUE TITLE
freesurfer - unable to load module due to missing ')' or ',' (my guess)

### ISSUE THREAD

**Issue by steelec** [gdevenyi/neuralabc_modules#6]
looked at the .lua, can't see any syntax errors except potentially that the basepath on line 14 is set without a pathJoin call - or potentially a "," is missing before basepath?

setenv("FREESURFER_HOME" basepath)

Error:
Unable to load module: freesurfer/6.0.0
     /opt/quarantine/modules/freesurfer/6.0.0.lua : [string
"conflict(myModuleName())..."]:14: ')' expected near 'basepath'

**Comment by gdevenyi** [comment]
Fixed.
