### ISSUE TITLE
paraview - server install does not include paraview binary

### ISSUE THREAD

**Issue by steelec** [gdevenyi/neuralabc_modules#7]
I think this is a server install? It does not come with the paraview binary, additional install required to perform interactive visualization.

Checked and confirmed that this was the case, downloaded the appropriate .tar.gz to my user's /Downloads/ParaView-5.6.0-MPI-Linux-64bit.tar.gz

**Comment by gdevenyi** [comment]
Where are the docs about this? I couldn't decide on which download to use. I just guessed

**Comment by steelec** [comment]
I couldn't find them either, but downloaded both available versions and
peeked inside.

**Comment by gdevenyi** [comment]
Fixed.
